FROM rust:1.93.1-slim AS builder
ENV RUSTFLAGS="-D warnings"
WORKDIR /veyora
COPY security-kernel/ ./security-kernel/
COPY backend/ ./backend/
COPY contracts/ ./contracts/
RUN --mount=type=cache,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,target=/veyora/backend/target,sharing=locked \
    cargo build --release --manifest-path backend/Cargo.toml -p sandbox && \
    cp backend/target/release/sandbox /veyora-sandbox

FROM debian:bookworm-slim
COPY --from=builder /veyora-sandbox /usr/local/bin/veyora-sandbox
ENTRYPOINT ["veyora-sandbox"]
