#!/usr/bin/env python3
"""Generate the release test plan from requirement IDs (PRD QA-012).

The plan is not a free-form checklist: every line is derived from the
feature/evidence registry (`release/features.json`) joined against the
PRD requirement table, and each requirement carries a pass/fail/blocked
verdict derived from the ledger's evidence — pass only when the registry
records automated evidence, blocked when the ledger names a blocker, fail
never by default (a failing requirement is a defect, not a plan state).

Usage:
    python3 tools/release/generate-test-plan.py [--output FILE] [--format md|json]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "release" / "features.json"
LEDGER = ROOT / "release" / "prd-progress.json"
PRD = ROOT / "PRD.md"


def prd_requirements() -> dict[str, str]:
    """Map requirement ID -> priority from the PRD tables."""
    table = {}
    for match in re.finditer(r"`([A-Z]{2,4}-[A-Z0-9]*-?\d{3})`\s*\|\s*(P[01])", PRD.read_text(encoding="utf-8"), re.M):
        table.setdefault(match.group(1), match.group(2))
    return table


def verdict(feature: dict, blockers: list[str]) -> str:
    # A recorded blocker on any requirement dominates: partial automation
    # never turns a blocked requirement into a pass.
    for blocker in blockers:
        if any(req in blocker for req in feature.get("requirement_ids", [])):
            return "blocked"
    return "pass" if feature.get("automated_evidence") else "blocked"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="-")
    parser.add_argument("--format", choices=["md", "json"], default="md")
    args = parser.parse_args()

    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))
    priorities = prd_requirements()
    blockers: list[str] = []
    for entry in ledger["backlog"]:
        blockers.extend(entry.get("remaining_scope") or [])

    plan = {
        "schema_version": 1,
        "generated_from": "release/features.json + release/prd-progress.json + PRD.md",
        "product_version": registry["product_version"],
        "lines": [],
    }
    for feature in registry["features"]:
        result = verdict(feature, blockers)
        plan["lines"].append({
            "feature": feature["feature_id"],
            "status": feature["status"],
            "requirement_ids": feature["requirement_ids"],
            "priorities": [priorities.get(req, "?") for req in feature["requirement_ids"]],
            "verdict": result,
            "automated_evidence": feature.get("automated_evidence", []),
            "pending_manual_evidence": feature.get("manual_evidence", []),
            "known_limitations": feature.get("known_limitations", []),
        })

    counts = {v: sum(1 for line in plan["lines"] if line["verdict"] == v)
              for v in ("pass", "blocked", "fail")}
    plan["verdict_counts"] = counts

    if args.format == "json":
        rendered = json.dumps(plan, indent=2) + "\n"
    else:
        rows = ["| Feature | Reqs (priority) | Verdict | Automated evidence | Pending manual |",
                "| --- | --- | --- | --- | --- |"]
        for line in plan["lines"]:
            reqs = " ".join(f"`{req}`({prio})"
                            for req, prio in zip(line["requirement_ids"], line["priorities"]))
            rows.append(
                f"| {line['feature']} ({line['status']}) | {reqs} | **{line['verdict']}** "
                f"| {len(line['automated_evidence'])} item(s) "
                f"| {len(line['pending_manual_evidence'])} item(s) |")
        rendered = (f"# Release test plan — {plan['product_version']}\n\n"
                    f"Generated by `tools/release/generate-test-plan.py` from the registry and "
                    f"ledger; verdicts: pass={counts['pass']} blocked={counts['blocked']} "
                    f"fail={counts['fail']}. A **blocked** verdict names missing evidence, never "
                    f"silence; a **fail** appears only when a defect is on record.\n\n"
                    + "\n".join(rows) + "\n")

    if args.output == "-":
        sys.stdout.write(rendered)
    else:
        (ROOT / args.output).write_text(rendered, encoding="utf-8")
        print(f"test plan written to {args.output} "
              f"(pass={counts['pass']} blocked={counts['blocked']} fail={counts['fail']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
